language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - '4.2.0'
  - 'node'
before_script:
  - npm prune
  - npm install -g gulp-cli
script: gulp test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
